#!/bin/sh

BUNDLE=$HOME/.vim/bundle
SHARE=$HOME/.vim/share
LOCK=$SHARE/bundle-$(date +"%Y%m%d-%H%M").lock

touch $LOCK
cd $BUNDLE
for d in $(find . -maxdepth 1 -mindepth 1 -type d -printf '%f\n'); do
    cd $d
    if [ -d .git ]; then
        # branch=$(git rev-parse --abbrev-ref HEAD)
        # echo $d:$branch
        if ! git diff-index --quiet HEAD; then
            echo $d
        fi
        # sha=$(git rev-parse --verify HEAD)
        # echo $d:$sha >> $LOCK
    else
        echo "NOT GIT: $d"
    fi
    cd $BUNDLE
done
