#!/bin/sh
#
# SPDX-FileCopyrightText: © 2014 Sebastián Mancilla <smancill@smancill.dev>
#
# SPDX-License-Identifier: MIT-0

vim=${VIM:-vim}

${vim} \
    --cmd 'profile start profile.log' \
    --cmd 'profile func *' \
    --cmd 'profile file *' \
    -c 'profdel func *' \
    -c 'profdel file *' \
    -c 'qa!' "$@"
