#!/bin/sh

BUNDLE=$HOME/.vim/bundle
LOCK=$1
PLUGIN=*

if [ $# -eq 2 ]; then
    PLUGIN=$2
fi

while read LINE
do
    NAME=$(echo $LINE | cut -d : -f 1)
    SHA=$(echo $LINE | cut -d : -f 2)
    case $NAME in
        $PLUGIN)
            echo "Restoring $NAME to $SHA"
            cd $BUNDLE/$NAME
            if git diff-index --quiet HEAD; then
                git reset --hard $SHA
                echo
            else
                echo "Cannot restore $NAME: dirty repo"
            fi
            ;;
    esac
done < $LOCK
